# Generated by Django 2.2.10 on 2021-01-11 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Poll's start date")),
                ('date_ended', models.DateTimeField(verbose_name="Poll's end date")),
                ('answer_type', models.CharField(choices=[('1', 'one answer'), ('N', 'N answers'), ('user_text', 'text_answers')], default='one choice', max_length=150)),
                ('passed_users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('passed_users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls_app.Poll')),
            ],
        ),
    ]
