# Generated by Django 2.2.10 on 2021-02-08 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='passed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_type',
            field=models.CharField(choices=[('1', 'one answer'), ('N', 'N answers'), ('user_text', 'text_answers')], default='1', max_length=150),
        ),
        migrations.AlterField(
            model_name='poll',
            name='passed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
