# Generated by Django 2.2.10 on 2021-02-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20210208_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image file'),
        ),
    ]
