# Generated by Django 2.2.10 on 2021-01-10 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_app', '0006_auto_20210111_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='passed_users',
        ),
        migrations.AddField(
            model_name='choice',
            name='passed_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='passed_users',
        ),
        migrations.AddField(
            model_name='poll',
            name='passed_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
